// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Follow struct {
	FollowingUserID int32
	FollowedUserID  int32
	CreatedAt       time.Time
}

type Post struct {
	ID    int32
	Title string
	// Content of the post
	Body      string
	UserID    int32
	Status    string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Role      string
	CreatedAt time.Time
}
